### ISSUE TITLE
Gebruik partials EJS

### ISSUE THREAD

**Issue by MokhtarAkle** [elina2022/connect-your-tribe-profile-card#1]
- Omdat we aan het oefenen zijn met EJS lijkt het mij handig om hier zoveel mogelijk gebruik van te maken om hier beter in te worden. Probeer daarom je head en onderkant van je ejs bestand in partials te zetten om deze vervolgens aan te roepen.

**Comment by elina2022** [comment]
Dankjewel voor de tip ik heb dit toegepast: 
![image](https://user-images.githubusercontent.com/112861148/218077199-a005cb3b-4d8a-4ab4-b094-e26ff285de6a.png)
