### ISSUE TITLE
onclick gebruik HTML

### ISSUE THREAD

**Issue by MokhtarAkle** [elina2022/connect-your-tribe-profile-card#3]
Probeer gebruik te maken van een externe JS bestand om script functies uit te voeren ipv onclick in de html

**Comment by elina2022** [comment]
In de sprints na deze heb ik dat inderdaad gedaan. Maar voor dit project heeft het denk niet heel veel nut meer om dit nog aan te passen omdat het hier meer ging om werken met node dan js.
